trigger:
  batch: true
  branches:
    include:
      - "*"

workspace:
  clean: all

steps:
  - task: NuGetToolInstaller@1
    displayName: 'Use NuGet 4.7.1'
    inputs:
      versionSpec: '4.7.1'

  - task: NuGetCommand@2
    displayName: 'Restore NuGet Packages'
    inputs:
      command: 'restore'
      restoreSolution: '**/*.sln'
      feedsToUse: 'select'
      vstsFeed: 'c5095ddb-6433-4990-a3a5-1df8a78b1302/$(FeedSecret)'

  - task: DotNetCoreCLI@2
    displayName: 'Build Function App'
    inputs:
      command: 'build'
      projects: 'src/**/*.csproj'
      arguments: '--configuration $(BuildConfiguration) --no-restore'

  - task: DotNetCoreCLI@2
    displayName: 'Run Unit Tests'
    inputs:
      command: test
      projects: 'src/**/*.UnitTests.csproj'
      arguments: '--configuration $(BuildConfiguration) --no-restore'

  - task: DotNetCoreCLI@2
    displayName: 'Publish Website'
    inputs:
      command: publish
      publishWebProjects: false
      projects: 'src/Dfe.Spi.EntitySquasher/Dfe.Spi.EntitySquasher.FunctionApp/Dfe.Spi.EntitySquasher.FunctionApp.csproj'
      arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)/publish --no-restore --no-build'

  - task: CopyFiles@2
    displayName: 'Copy ARM template'
    inputs:
      Contents: |
        azure/*
      TargetFolder: '$(build.artifactstagingdirectory)/publish'
      OverWrite: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)/publish'