trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: DotNetCoreCLI@2
    displayName: 'Build Function App'
    inputs:
      command: 'build'
      projects: 'src/Dfe.Spi.EntitySquasher/Dfe.Spi.EntitySquasher.Functions/Dfe.Spi.EntitySquasher.Functions.csproj'
      arguments: '--configuration Release --output $(Build.BinariesDirectory)'