trigger:
  batch: true
  branches:
    include:
      - "*"

workspace:
  clean: all

variables:
  BuildConfiguration: 'Release'
  BuildPlatform: 'Any CPU'

steps:
  - task: NuGetToolInstaller@1
    displayName: 'Use NuGet 4.7.1'
    inputs:
      versionSpec: '4.7.1'

  - task: NuGetCommand@2
    displayName: 'Restore NuGet Packages'
    inputs:
      command: 'restore'
      restoreSolution: '**/*.sln'
      feedsToUse: 'select'
      vstsFeed: 'c5095ddb-6433-4990-a3a5-1df8a78b1302/$(FeedSecret)'

  - task: DotNetCoreCLI@2
    displayName: 'Build Function App'
    inputs:
      command: 'build'
      projects: 'src/**/*.csproj'
      arguments: '--configuration $(BuildConfiguration) --no-restore'

  - task: DotNetCoreCLI@2
    displayName: 'Run Unit Tests'
    inputs:
      command: test
      projects: 'src/**/*.UnitTests.csproj'
      arguments: '--configuration $(BuildConfiguration) --no-restore'

  - task: DotNetCoreCLI@2
    displayName: 'Publish Squasher App'
    inputs:
      command: publish
      publishWebProjects: false
      projects: 'src/Dfe.Spi.EntitySquasher/Dfe.Spi.EntitySquasher.FunctionApp/Dfe.Spi.EntitySquasher.FunctionApp.csproj'
      arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/publish --no-restore --no-build'

  - task: DotNetCoreCLI@2
    displayName: 'Publish acdf-gen'
    inputs:
      command: publish
      publishWebProjects: false
      projects: 'src/Dfe.Spi.EntitySquasher/Dfe.Spi.EntitySquasher.AcdfGen.ConsoleApp/Dfe.Spi.EntitySquasher.AcdfGen.ConsoleApp.csproj'
      arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/acdf-gen --no-restore --no-build'

  - task: CopyFiles@2
    displayName: 'Copy ARM template'
    inputs:
      Contents: |
        azure/*
      TargetFolder: '$(Build.ArtifactStagingDirectory)/publish'
      OverWrite: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Squasher App'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/publish'

  - task: DotNetCoreCLI@2
    displayName: 'Run acdf-gen'
    inputs:
      command: 'custom'
      custom: '$(Build.ArtifactStagingDirectory)/acdf-gen/Dfe.Spi.EntitySquasher.AcdfGen.ConsoleApp/acdf-gen.dll'
      arguments: '--filename acdf-default.json --adapterNames GIAS UKRLP'
      workingDirectory: '$(Build.ArtifactStagingDirectory)/acdf-gen/Dfe.Spi.EntitySquasher.AcdfGen.ConsoleApp'

  - task: CopyFiles@2
    displayName: 'Copy Generated ACDF'
    inputs:
      Contents: $(Build.ArtifactStagingDirectory)/acdf-gen/Dfe.Spi.EntitySquasher.AcdfGen.ConsoleApp/acdf-default.json
      TargetFolder: '$(Build.ArtifactStagingDirectory)/publish'
      OverWrite: true